password = ""

[connections.snowflake]
account = ""
user = ""
password = ""
role = ""
database = ""
schema = ""
warehouse = ""
client_session_keep_alive = true

[azure]
path=""

[sponsorship]
path=""

[sponsorship2]
path=""

[billing]
path=""

[eod]
path=""

[datasource]
source=2
