[connections.snowflake]
account = "pdhezsm-jq54078"
user = "shaunmis"
password = "RYMM9*25^hjc$6W&8Nh6bBnNsqkJf!jv"
role = "ACCOUNTADMIN"
database = "DB_MIS"
schema = "AZURE"
client_session_keep_alive = true